### ISSUE TITLE
Fails on JSXSpreadAttribute

### ISSUE THREAD

**Issue by HorizonXP** [bohdanbirdie/react-css-modules.macro#8]
https://github.com/bohdanbirdie/react-css-modules.macro/blob/094d1adfa4bce3e3c56821ed2fceb308de642027/src/macro.js#L54

That line seems to fail when it encounters a JSXSpreadAttribute, which does not have a `name` property.

**Comment by bohdanbirdie** [comment]
@HorizonXP could you please provide an example of the code that is failing?

**Comment by HorizonXP** [comment]
@bohdanbirdie Sure. I have a PR ready too.

```javascript
const CustomButton = props => (
  <button {...props} styleName="custom-button">
    Our Custom Button!
  </button>
)
```

**Comment by bohdanbirdie** [comment]
@HorizonXP ok, cool
submit it and I will take a look in a few days if nothing else going to be on the priority list
